/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testcontainer.sample;

import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.junit.jupiter.api.Assertions.*;

@Testcontainers
class LibraryTest {

    @Container
    private GenericContainer  helloWorld = new GenericContainer<>("hello-world");

    @Test void testSomeLibraryMethod() {
        assertTrue(helloWorld.getLogs().contains("Hello from Docker!"));
    }
}
